### ISSUE TITLE
Gallery images on receiver sites not showing all images

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#147]
**Describe the bug**
When gallery images are pushed to receiver sites, all media gets moved, gallery block gets created, but only one image shows up in the gallery (instead of multiple like at source)

**To Reproduce**
Create source post with gallery of images
Push to receiver sites
Check receiver sites - media library has all images (and they're all associated with the correct post), gallery block on post created, but only one image in gallery block.

**Buggy Post**
Link to existing post where this issue appeared: https://datareceiver2.copperleaf.dev/image-testing-to-post/

**Which receiver?** All of them

**Testing that was occurring before this test**

Testing featured image sync, then content image sync (both went well)

**Expected behavior**

All gallery images should come through to galleries

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [Chrome
 - Version Version 78.0.3904.108 (Official Build) (64-bit) (updated since last report)

**Comment by GraysonE** [comment]
@copperleaf this might not be something I can fix. It has to do with something happening in wp_generate_attachment_metadata(). Either this is an unfortunately massive overhaul, or a quick setting. Essentially, this function is appending "-scaled" to the end of the file name, flipping the orientation, and then creating every size ("1024x768" and others) based off of that flipped image. The reason this isn't showing up in the gallery is because it's now "768x1024" instead of "1024x768." WOW. Annoying. I'm going to play with some settings because I'm not sure this is something I can code.

**Comment by GraysonE** [comment]
https://wordpress.org/support/topic/images-rotated-sideways/

**Comment by GraysonE** [comment]
The only thing I can find about this is the image's EXIF metadata might be telling WordPress to rotate the image because of the orientation setting. I read that this happens a lot with iPhones. . . Not sure if those photos were taken on an iPhone or not. For now, I think we should skip this bug because it is seeming like a pretty deep rabbit hole.

**Comment by GraysonE** [comment]
@copperleaf this has to do with an image's EXIF metadata. Specifically the orientation value. This must be telling WordPress to correct the orientation after generating attachment metadata. I'm not sure I can fix this.

**Comment by GraysonE** [comment]
@copperleaf OMG. I downloaded the sideways bottle photo and it was right side up.

**Comment by GraysonE** [comment]
@copperleaf Just synced after using the plugin to reorient on upload and it all works again. :O
