### ISSUE TITLE
Disabling a known CPT at receiver doesn't work and causes issues

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#161]
**Describe the bug**
I've created posts in Ducks3 (new CPT) and tried to disable both #2 receivers from receiving ducks3 post type. When I "overwrite all receivers" or "sync all" the system hits an error (either failed fetch or server error). If I try to sync again, the source overrides the settings at receivers (forcing ducks on the receivers that clearly said "no ducks") and then sends multiple copies of the post to all receivers. 

**To Reproduce**
I've disabled ducks3 from both receiver2 and multi2 for you (go check if you like: https://datareceiver2.copperleaf.dev/wp-admin/admin.php?page=data-sync-options , https://multi2.copperleaf.dev/wp-admin/admin.php?page=data-sync-options)
At source, create a new post in Ducks3
Try to sync that post. :) 

**Which receiver?**
Link to existing post where this issue appeared: any receiver that changed it's mind about receiving a post type

**Expected behavior**
No means no. If the receiver says no Ducks3 (after the initial creation and push from source), source should respect it's right to say no instead of forcing more ducks. It should only force the ducks3 on first push when it's NEW (the receiver hasn't seen this post type before).

**Comment by GraysonE** [comment]
@copperleaf so at some point Receiver 1's site id and source site url data got deleted. This caused a bunch of errors. I don't understand how that happened. Also, it looks like if you just click sync again it works. I'm having a hard time with this one, but since it already works now that I repaired the site id and source site url info on Receiver 1 and 2, we should be good. Maybe we should get on a call and walk through what you were doing before all of this happened?

**Comment by GraysonE** [comment]
Check delete function to see if it updates any wp_options
